# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savedata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='age',
        ),
        migrations.DeleteModel(
            name='location',
        ),
        migrations.RemoveField(
            model_name='name',
            name='name_text',
        ),
        migrations.AddField(
            model_name='name',
            name='age',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name',
            name='location',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name',
            name='name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
